# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: "我的 Gemini"
    provider: openai
    model: "gemini-3.1-pro-preview"
    apiKey: "sk-pbQ6zUAWe10aF6b2001ET3BlBKFJ6FB46B9dE9eB4d5bbeD1"
    apiBase: "https://api.ohmygpt.com/v1"
# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp

tabAutocompleteModel:
  name: "自动补全"
  provider: openai
  model: "gemini-3.1-pro-preview"
  apiKey: "sk-pbQ6zUAWe10aF6b2001ET3BlBKFJ6FB46B9dE9eB4d5bbeD1"
  apiBase: "https://api.ohmygpt.com/v1"
